version: '3'

services:
  mysql:
    image: mariadb:10.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=couch_film_critic_db
    ports:
      - '3306:3306'
    volumes:
       - '../SQL/tables.sql:/docker-entrypoint-initdb.d/tables.sql'
       - reviews_mysql_data:/var/lib/mysql
volumes:
  reviews_mysql_data:
