environment: "local" # local, dev, prod
templates_path: "./ui/html/"
dsn: "root@tcp(localhost:3306)/couch_film_critic_db?&charset=utf8&interpolateParams=true&parseTime=true"
jwt_secret: "SECRET_KEY"
hash_pass_options:
  time: 5
  memory: 65536
  threads: 2
http_server:
  address: "127.0.0.1:8081"
  timeout: 3s
  idle_timeout: 60s